# Generated by Django 4.1.4 on 2022-12-12 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_category_topic_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
